export const NEW_SYNC_ROOM_GAME_KEYS = [
  "yamanote",
  "two-choice",
  "word-wolf",
  "ng-word",
  "impression-ranking",
  "party-pack",
  "johari-window",
  "turtle-soup",
  "anonymous-box",
  "majority-game",
  "truth-lie-game",
  "count-up-game",
  "reverse-word-game",
  "song-association-quiz",
  "drawing-quiz",
  "hazard-card-game",
  "fast-typing-game",
  "memory-drawing-game",
  "value-meter-game",
  "acting-game",
  "party-sugoroku",
  "territory-board-game",
  "funny-line-karuta",
  "emo-hint-game",
  "resource-negotiation-game",
  "life-event-sugoroku",
  "arm-wrestling-tournament",
  "safe-random-draw",
  "person-hint-quiz",
  "large-majority-game",
  "humming-intro-quiz",
  "loanword-ban-game",
  "werewolf-game",
] as const;

export const NATIVE_SYNC_ROOM_GAME_KEYS = [
  "yamanote",
  "ng-word",
  "turtle-soup",
  "party-pack",
  "two-choice",
  "impression-ranking",
  "majority-game",
  "johari-window",
  "anonymous-box",
  "word-wolf",
  "werewolf-game",
  "truth-lie-game",
  "reverse-word-game",
  "fast-typing-game",
  "memory-drawing-game",
  "value-meter-game",
  "acting-game",
  "loanword-ban-game",
  "song-association-quiz",
  "drawing-quiz",
  "funny-line-karuta",
  "emo-hint-game",
  "person-hint-quiz",
  "humming-intro-quiz",
] as const;

export function isNewSyncRoomGameKey(key: string) {
  return (NEW_SYNC_ROOM_GAME_KEYS as readonly string[]).includes(key);
}

export function isNativeSyncRoomGameKey(key: string) {
  return (NATIVE_SYNC_ROOM_GAME_KEYS as readonly string[]).includes(key);
}
